version: '3.7'
services:
    flask:
        build: .
        ports:
            - "5000:5000"
        environment:
            - REDIS_HOST=redis
            - MONGO_HOST=mongodb
            - FLASK_ENV=development
        depends_on:
            - mongodb
    redis:
        image: redis:5.0.7
    mongodb:
        image: mongo:4.2.3
        ports:
            - "27017:27017"